---
title: "20211215 - rarefraction curves Plastid fraction - Charlotte Eckmann"
author: Fabian Wittmers
date: December 15 2021
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE,
                      fig.path = "figures/",
                      dpi = 300)

```


```{r, echo = TRUE, message = FALSE, warning = FALSE}

# core packages
library(tidyverse)
library(ggplot2)
library(reshape2)

# plotting extension
library(patchwork)
library(scales)
library(ggnewscale)
library(ggtext) #for text formatting in ggplots

# color palette libraries:
library(RColorBrewer)
library(wesanderson)

# others
library(janitor)
library(lubridate) #for date formatting
library(XML) #to read biosamples xml
library(methods) # to process biosamples xml
library(finalfit) # for data  exploration (and missing data)
library(ggdendro) #Extracting the dendrogram plot data using dendro_data()
library(vegan) #bio data analysis, e.g. rarefraction

#for rarefraction analysis
#BiocManager::install("phyloseq")
library(phyloseq)

#logical arguments
`%notin%` <- Negate(`%in%`)

```

+ getting metadata for the feature tablee

```{r, message=FALSE, warning=FALSE}
#this is a modified version where I changed the V1V2 name format to match the feature table

metadata <- readxl::read_excel("~/Downloads/BATS_BS_COMBINED_MASTER_2021.12.17_cae.xlsx",sheet = 6) %>%
  separate_rows(V1V2_ID,sep = ";") %>%
  relocate(V1V2_ID) %>%
  #na_if("-999.0") %>% #convert character -999.0 to NA
  #na_if(-999) %>% #convert -999 to NA
  select(which(colMeans(is.na(.)) < 1)) %>% #removing every col that is all NA
  filter(!is.na(yyyymmdd),
          !is.na(`time(UTC)`)) %>%
  mutate(date = as.Date(as.character(yyyymmdd),format="%Y%m%d", ordered = T),
         time = gsub("([0-9])([0-9])([0-9])$", "\\1:\\2\\3" , `time(UTC)`), # first time column transformation
         time = gsub("(^[0-9]):", "0\\1:" , time), # second time column transformation
         year = as.factor(format(date, "%Y")),
         month = as.factor(format(date, "%m")),
         date_time = as.character(paste(date, time), format="%m-%d-%Y %H:%M")) # as.character essential, doesn't work 

metadata <- metadata %>%
  select(V1V2_ID, Nominal_Depth) %>%
  filter(!is.na(V1V2_ID), 
         Nominal_Depth < 310)

metadata

#samples used in paper
paper_samples <- read.csv("/Users/ceckmann/Desktop/bats_2016_2019/metadata/lists/paper_samples.csv")

```

import feature table 

```{r}

feature <- read_tsv("/Users/ceckmann/Desktop/bats_2016_2019/og_data_Fabian/feature_table.tsv",
                    col_types = cols(.default = col_double(), seqname = col_character()),
                    col_names = TRUE) %>%
  #select(-c(viridi, cyano, cyanoplastid, strameno, pelago, dictyo)) %>%
  pivot_longer(cols = -seqname, names_to = "V1V2_ID") %>%
  filter(V1V2_ID %in% metadata$V1V2_ID) %>%
  filter(V1V2_ID %in% paper_samples$V1V2_ID) %>%
  pivot_wider(names_from = "V1V2_ID", values_from = "value") %>%
  column_to_rownames(var = "seqname") %>%
  select(which(!colSums(., na.rm=TRUE) %in% 0))

feature

#argh which ones are missing??

missing <- paper_samples %>% filter(!V1V2_ID %in% metadata$V1V2_ID)
```

create rarefraction dataframe

```{r, warning = FALSE, echo = FALSE, results = 'hide', include = FALSE}

len <- dim(feature)[2] #number of samples

raref_data <- tibble(a=character(), b=numeric()) #empty tibble to store results in

for (i in c(1:len))  { #looping through the 401 samples
  print(i)
  sam <- colnames(feature)[i] #the sample name
  out <- rarecurve(t(feature[i]), step = 25, label = FALSE,
                   #col = metadata$Nominal_Depth,
                   ylab = "ASVs",
                   xlab = "sample size") #compute rarefraction curve
  x <- attr(out[[1]],"Subsample")
  points <- out[[1]] %>% # curve values for sample i
    as_tibble() %>%
    cbind(x) %>%
    rename(y = value) %>%
    mutate(sample = sam)
  raref_data <- rbind(raref_data, points)
}

```

```{r}

# rarefraction curves of the original feature table. 
# backed up here because raref_data later overwritten
orig_feat_curves <- raref_data 

orig_feat_curves %>%
  #filter(sample %in% c("May16_1978m_1800m","May16_1018m_300m", "May16_1978m_1900m") %>% #testing
  ggplot(aes(x = x, y = y, fill = sample)) +
  geom_line(size = 0.5) +
  theme_light() +
  ggtitle("rarefraction curves") +
  scale_x_continuous(name = "read count") +
  scale_y_continuous(name = "ASVs") +
  theme(panel.grid = element_blank())

```


```{r}

options(scipen = 1000000)


colorscheme <- c( "1" = "#ED2590",
                  "20"="lightblue",
                 "40" = "#00A14B",
                 "80" = "#00AEEF",
                 "100" = "#363795",
                 "120" = "#662D91",
                 "140" = "grey",
                 "160" = "orange",
                 "200" = "darkolivegreen4",
                 "250" = "yellow4",
                 "300" = "black")
  

curves_per_depth <- orig_feat_curves %>%
  rename(V1V2_ID = sample) %>%
  left_join(metadata, by = "V1V2_ID") %>%
  rename(Depth = Nominal_Depth) %>%
  filter(Depth %notin% c(10, 150)) %>% #get rid of the depth only present a handfull times
  mutate(Depth = factor(Depth)) %>% 
  ggplot(aes(x = x, y = y)) +
  geom_line(aes(color = Depth, group = V1V2_ID), size = 0.5) +
  ggtitle(label = NULL) +
  scale_x_continuous(name = "\nAbsolute Reads") +
  scale_y_continuous(name = "ASVs") +
  scale_color_manual(values = colorscheme,
                    name = "Depth") +
  theme_light() +
  theme(panel.grid  = element_blank(),
        panel.border = element_rect(color = "black", size = 0.75),
        axis.ticks   = element_line(color = "black", size = 0.5),
        axis.text.y = element_text(angle = 90, hjust = 0.5),
        strip.background = element_blank()) +
  facet_wrap(~Depth, nrow = 2) + guides(color = FALSE) # color legend in part of other figures legend -> only collecting one in the composite plot

curves_per_depth

#curves_per_station %>%
ggsave(filename = "all_asvs_rarefaction_curves.pdf", height = 5, width = 10, device = "pdf")

```

compute slopes

```{r, warning=FALSE, message=FALSE}

len <- dim(feature)[2] #number of samples

sample_total_reads <- feature %>%
  rownames_to_column(var = "name") %>%
  pivot_longer(cols = -name, names_to = "sample", values_to =  "copies") %>%
  group_by(sample) %>%
  summarise(sum = sum(copies)) %>%
  column_to_rownames(var = "sample")

rareslope_results <- list() #empty tibble to store results in
n=0

for (i in c(1:len)) { #looping through the 177 samples
  #print(i)
  n = n+1
  sam <- colnames(feature)[i] #the sample name
  
  sample_reads <- sample_total_reads[rownames(sample_total_reads) == sam,] #total reads (copies)
  
  out <- rareslope(x = t(feature[i]), 
          sample = sample_reads - 1) #if take the full sample (ie read copies in the samples), slope becomes 0 
  
  slope <- as_tibble(out) %>%
    as_vector()

  rareslope_results[[n]] <- c(sam, slope)
}

vegan_slopes <- rareslope_results %>%
  data.frame() %>% t() %>% as_tibble() %>%
  arrange(desc(value))

vegan_slopes

```

plotting  / visualisation

```{r}

slope_by_depth <- vegan_slopes %>%
  rename(V1V2_ID = V1) %>%
  left_join(metadata, by = "V1V2_ID") %>%
  rename(Depth = Nominal_Depth) %>%
  filter(Depth %notin% c(10, 150)) %>% #get rid of the depth only present a handfull times
  mutate(slope = as.double(value),
         depth_f = factor(Depth)) %>%
  filter(slope < 0.5) %>%
  ggplot(aes(x = slope, y = Depth)) +
  geom_point(aes(color = depth_f), size = 2, alpha = 0.5) +
  scale_color_manual(values = colorscheme,
                     name = "Depth") +
  scale_y_continuous(name = "\nDepth (m)") +
  scale_x_continuous(name = "Rarefraction curve final slope\n") +
  theme_light() +
  theme(panel.grid   = element_blank(),
        panel.border = element_rect(color = "black", size = 0.75),
        axis.ticks   = element_line(color = "black", size = 0.5)) +
  coord_flip() + guides(color = guide_legend(override.aes = list(alpha = 1)))

slope_by_depth

#slope_by_depth %>%
ggsave(filename = "all_asvs_rarefaction_final_slopes.pdf", height = 4, width = 6, device = "pdf")

```

as jitter

```{r}

options(scipen = 10)

slope_by_depth_2 <- vegan_slopes %>%
  rename(V1V2_ID = V1) %>%
  left_join(metadata, by = "V1V2_ID") %>%
  rename(Depth = Nominal_Depth) %>%
  filter(Depth %notin% c(10, 150)) %>% #get rid of the depth only present a handfull times
  mutate(slope = as.double(value),
         depth_f = factor(Depth)) %>%
  #filter(slope < 0.5) %>%
  ggplot(aes(y = slope, x = depth_f)) +
  geom_jitter(aes(color = depth_f), size = 2, alpha = 0.3) +
  geom_hline(aes(yintercept = 1e-01), lty = 5, color = "grey30") +
  scale_color_manual(values = colorscheme,
                     name = "Depth (m)") +
  scale_x_discrete(name = "\nDepth (m)") +
  scale_y_continuous(name = "Rarefraction curve final slope\n", 
                     trans = "log10", 
                     breaks = c(1,1e-1,1e-2,1e-5,1e-10, 1e-15, 1e-20),
                     expand = c(0.05,0)) +
  theme_light() +
  theme(panel.grid   = element_blank(),
        panel.border = element_rect(color = "black", size = 0.75),
        axis.ticks   = element_line(color = "black", size = 0.5)) +
  guides(color = guide_legend(override.aes = list(alpha = 1))) +
  annotation_logticks(sides = "l", outside = FALSE, base = 10)

slope_by_depth_2

#slope_by_depth %>%
ggsave(filename = "all_asvs_rarefaction_final_slopes_depth.pdf", height = 4, width = 6, device = "pdf")

```

```{r}

## using sample colorsheme and labelling as in plots above

sample_to_reads <- feature %>%
  rownames_to_column("ASV") %>%
  pivot_longer(cols = -ASV) %>%
  group_by(name) %>%
  summarise(sample_reads = sum(value)) %>%
  rename(V1 = name)


slope_by_seqs <- vegan_slopes %>%
  left_join(sample_to_reads, by = "V1") %>%
  rename(V1V2_ID = V1) %>%
  left_join(metadata, by = "V1V2_ID") %>%
  rename(Depth = Nominal_Depth) %>%
  filter(Depth %notin% c(10, 150)) %>% #get rid of the depth only present a handfull times
  mutate(slope = as.double(value)) %>%
  #filter(slope < 0.5) %>%
  ggplot(aes(y = slope, x = sample_reads)) +
  geom_point(aes(color = factor(Depth)), size = 2, alpha = 0.3) +
  geom_hline(aes(yintercept = 1e-01), lty = 5, color = "grey30") +
  scale_color_manual(values = colorscheme,
                     name = "Depth (m)") +
  scale_x_continuous(name = "\nAmplicon Reads (all)", trans = "log10") +
  scale_y_continuous(name = "Rarefraction curve final slope\n", 
                     trans = "log10", 
                     breaks = c(1,1e-1,1e-2,1e-5,1e-10, 1e-15, 1e-20),
                     expand = c(0.05,0)) +
  theme_light() +
  theme(panel.grid   = element_blank(),
        panel.border = element_rect(color = "black", size = 0.75),
        axis.ticks.x  = element_line(color = "black", size = 0.5),
        axis.ticks.y = element_blank(),
        axis.text.y = element_blank(),
        axis.title.y = element_blank()
        ) +
  guides(color = FALSE) +
  annotation_logticks(sides = "lb", outside = FALSE, base = 10)

slope_by_seqs

ggsave(filename = "all_asvs_rarefaction_final_slopes_reads.pdf", height = 4, width = 4.5, device = "pdf")

```


```{r}

design <- "CC
BA
"

patchwork::wrap_plots(B = slope_by_seqs, A = slope_by_depth_2, C = curves_per_depth) +
  plot_layout(guides = "collect", design = design) + patchwork::plot_annotation(tag_levels = "A")

ggsave(filename = "rarefraction_all_just_paper_samples.pdf", height = 9, width = 10, device = "pdf")

```





